version: '3.7'

services:
  bd:
    container_name: postgres-boardly
    image: postgres:latest
    ports:
      - 5440:5432
    restart: always

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: